### ISSUE TITLE
Unable to install snappy in node.js v18.12.1

### ISSUE THREAD

**Issue by punit1108** [Brooooooklyn/snappy#114]
<img width="625" alt="Screenshot 2023-02-01 at 6 45 16 PM" src="https://user-images.githubusercontent.com/7887355/216053412-b4cb9fe9-239b-41d9-8d1c-1c60245f0624.png">

**Comment by Brooooooklyn** [comment]
@punit1108 how could I reproduce it?

**Comment by punit1108** [comment]
Invalid Issue. The problem was with my incompatible project restrictions on node and npm version. Fixed it and now i am able to run snappy.

Thanks for you quick reply.
