### ISSUE TITLE
Take over official snappy package on npm

### ISSUE THREAD

**Issue by kesla** [Brooooooklyn/snappy#16]
Hi!

Are you interested in taking over the snappy-package on npm? 

`snappy` is the first serious npm module I ever published, so I gotta be honest that it'll be a bit difficult to let it go, but since this project is snappier than mine, I think it would make sense.

My suggestion would be that I add you as a maintainer to the snappy package and that you publish a new version of it (as version  7.0.0 so that no existing installations of snappy are affected).
I would than also deprecate my repo on github, sending them your way instead.

Let me know what you think about my suggestion, I think it would be a cool thing to do.

**Comment by Brooooooklyn** [comment]
Oh it's very coooooooool!!
Thank you for being so much affirmation of my project, I'm very excited.

> My suggestion would be that I add you as a maintainer to the snappy package and that you publish a new version of it (as version 7.0.0 so that no existing installations of snappy are affected).

Yes. after this I will write a migration guite in `README` to help people upgrade to this project.

**Comment by Brooooooklyn** [comment]
@kesla Hey I've opened a pull request here to finish the package rename job: https://github.com/Brooooooklyn/snappy/pull/new/snappy-7

Feel free to review and leave some comments on it!

**Comment by kesla** [comment]
Very cool, the PR's looking good.

I added you as a maintainer to snappy on npm.

I'll deprecate my repo once you've published this as version 7 on npm!

**Comment by kesla** [comment]
I saw that you did a release of snappy 7, coming from this repo. Very cool!
I'm also referring people to your project from https://github.com/kesla/node-snappy - so I think that that means we're done & that this can be closed, right?

**Comment by Brooooooklyn** [comment]
Yes，thanks again！

**Comment by adityapatadia** [comment]
Doe to this change, something went wrong and this library does not work well with mongodb nodejs driver now in v7.0.

**Comment by Brooooooklyn** [comment]
@adityapatadia I will take a look soon

**Comment by kdybicz** [comment]
@adityapatadia it might, as library API has slightly changed and ie. `uncompressSync` doesn't support returning `string` anymore. I've just fall for the same issue.

**Comment by Brooooooklyn** [comment]
https://github.com/Brooooooklyn/snappy/pull/21

**Comment by Brooooooklyn** [comment]
See https://github.com/Brooooooklyn/snappy/releases/tag/v7.0.2, `{ asBuffer: boolean }` option landed

**Comment by cstmgl** [comment]
> Oh it's very coooooooool!! Thank you for being so much affirmation of my project, I'm very excited.
> 
> > My suggestion would be that I add you as a maintainer to the snappy package and that you publish a new version of it (as version 7.0.0 so that no existing installations of snappy are affected).
> 
> Yes. after this I will write a migration guite in `README` to help people upgrade to this project.

Hi , any chance you can point me to that migration guide for people using the old API?
