### ISSUE TITLE
MongoDB driver compatible issue

### ISSUE THREAD

**Issue by Brooooooklyn** [Brooooooklyn/snappy#23]

**Comment by nbbeeken** [comment]
Hi @Brooooooklyn thanks for taking on ownership of the Snappy lib, I'm an engineer on the MongoDB Node.js driver and we've already solved the issue in our 4.x driver here: https://github.com/mongodb/node-mongodb-native/pull/2939 and will be doing a similar patch in our 3.x version.

**Comment by Brooooooklyn** [comment]
Oh that is amazing!
