### ISSUE TITLE
Optional dependencies are not installed

### ISSUE THREAD

**Issue by xamgore** [Brooooooklyn/snappy#30]
Hi! The package `@napi-rs/snappy-darwin-x64` is not derived after the installation of the latest `snappy`. What may be the reason? `Can not load bindings` also appears until the latter is installed. 

```
$ npm -v
7.11.2
```

**Comment by Brooooooklyn** [comment]
Did you install with `--ignore-optional` flag?

**Comment by Brooooooklyn** [comment]
Tested on my macOS 11.5, Node.js @16.7.0, npm@7.20.3, everything is fine.

**Comment by xamgore** [comment]
The flag drops installation of optional packages, though my problem is the opposite. They are not installed at all, but I need them to be installed. Ok, I will try the newest version of npm, maybe there is a bug there.

**Comment by sugarandmagic** [comment]
Same issue here, we develop on macs, run in docker, the latest version is not pulling in the correct packages even when I omit --ignore-optional

**Comment by Brooooooklyn** [comment]
@sugarandmagic Yes you can not omit `--ignore-optional` flag if you install dependencies in macOS and run your app in Linux(Docker). It's by design.
