### ISSUE TITLE
Search ldd in the $PATH

### ISSUE THREAD

**Issue by getkey** [Brooooooklyn/snappy#81]
I get the following crash on NixOS:

```
Error: ENOENT: no such file or directory, open '/usr/bin/ldd'
```

On NixOS, `ldd` is in an exotic location:

```sh
> which ldd
/run/current-system/sw/bin/ldd
```

**Comment by fehnomenal** [comment]
I encountered the same error.

I'm using node2nix and had success with the following:
```nix
nodePackages // {
  foo = nodePackages.foo.override {
    preRebuild = ''
      sed -i 's|/usr/bin/ldd|${pkgs.glibc.bin}/bin/ldd|' node_modules/snappy/index.js
    '';
  };
}
```

**Comment by Brooooooklyn** [comment]
Fixed in the latest release

**Comment by Brooooooklyn** [comment]
Fixed in https://github.com/Brooooooklyn/snappy/commit/dbd61db3de57921bf6c6f6acd809093ba417ea26 for reference
